# Bases de Schauder en espacios vectoriales normados.

Es bien conocido que todo espacio vectorial tiene base de Hamel. Es decir, en todo espacio vectorial podemos encontrar un conjunto de vectores linealmente independientes cuyas combinaciones lineales (¡finitas!) generan el espacio. Además, todas las bases de Hamel de un mismo espacio vectorial tienen algo en común: su cardinal. Por tanto, es posible definir la _dimensión_ de cualquier espacio vectorial.

No obstante, en el caso de dimensión infinita, la exigencia de finitud de las combinaciones lineales provoca que las bases de Hamel pierdan gran parte de su utilidad. Más exactamente (véase  @BST[pág. 48]):

<!-- \begin{theorem}
Ningún espacio vectorial de dimensión infinita admite base de Hamel numerable. 
\end{theorem} -->

::: {#thm-first}

Ningún espacio vectorial de dimensión infinita admite base de Hamel numerable.

:::

 
Evidentemente, la no numerabilidad de una base es un gran inconveniente, pues reduce enormemente la capacidad de trabajar con éstas: con una base nosotros queremos reducir el número de elementos que necesitamos conocer de un espacio para poder trabajar con él, pero si dicha base es no numerable entonces es necesario conocer casi tantos elementos como tiene el espacio, lo cual hace redundante el sentido de una base.

Para superar la problemática anteriormente mencionada podemos buscar ayuda en la topología y emplear el concepto de convergencia para generalizar las combinaciones lineales finitas a sumas infinitas, es decir, a series.

Sea $(X,\|\!\cdot\!\|)$ un espacio vectorial normado.
<!--
\begin{definition}[Base de Schauder]\hspace*{1mm}\\
\label{def:bs}
\end{definition}
-->

::: {#def-bs}

## Base de Schauder
\hspace*{1mm}

Se dice que una sucesión $(e_i)_i\subset X$ es una *base de Schauder de $X$* si para cada vector $x\in X$ existe una única sucesión de escalares $(a_i)_i$ de modo que  
$$
x=\sum_{i=1}^{\infty}{a_ie_i},
$$

es decir, cumpliendo que  
$$
\lim_{n\rightarrow\infty}\big\|x-\sum_{i=1}^{n}{a_ie_i}\big\|=0.
$$

:::


La anterior definición ya nos deja entrever esa similitud de las bases de Schauder con las de Hamel: un conjunto de vectores---linealmente independientes--- que generan el espacio y nos permiten asignar de forma única unos coeficientes a todos los elementos de dicho espacio. Hasta aquí tenemos la filosofía algebraica del Análisis Funcional. 

El lector podrá notar ahora los beneficios de introducir una perspectiva analítica, o más bien topológica, al poder reducir el tamaño de las bases. Donde antes teníamos bases no numerables para espacios de dimensión infinita, ahora tenemos una sucesión numerable que genera todo el espacio manteniendo la unicidad de los coeficientes (que tienen entonces derecho a ser denominados *coordenadas*). Parece que vamos por buen camino en el cumplimiento de nuestro objetivo.

Veamos ahora una caracterización de estas bases que nos será muy útil tanto para demostrar que una sucesión es, en efecto, base de Schauder como para construirlas.

<!-- \begin{definition}(Proyecciones canónicas de una base de Schauder)\hspace*{1mm}\\
\end{definition} -->


::: {#def-ProyeccionesCanonicas}

## Proyecciones canónicas de una base de Schauder
\hspace{1mm}

Si $(e_i)_i$ es una base de Schauder de $X$, la sucesión de \emph{proyecciones canónicas} asociada a $(e_i)_i$ es la sucesión de operadores $(P_n)_n\subset\mathcal{B}(X)$ dada, para cada $n\in\mathbb{N}$, por
$$
    P_n\colon x=\sum_{i=1}^\infty a_ie_i\in X\longmapsto P_nx=\sum_{i=1}^n a_ie_i\in X.
$$ {#eq-ProyCanon}

:::


Sea $(X,\|\!\cdot\!\|)$ un espacio vectorial normado con base de Schauder $(e_i)_i$.

<!-- \begin{proposition}[Caracterización de las proyecciones canónicas]\label{proyections}\hspace*{1mm}\\ -->

::: {#thm-proyecciones}

## Caracterización de las proyecciones canónicas
\hspace*{1mm}

La sucesión de proyecciones canónicas asociada a $(e_i)_i$ satisface las siguientes propiedades:

<!-- \begin{itemize} -->
(a) para cada $n\in\mathbb{N}$, $P_n(X)$ es un espacio vectorial de dimensión $n$;

(b) para cualesquiera $n,\,m\in\mathbb{N}$, $P_nP_m=P_mP_n=P_{\min\{n,m\}}$;

(c) para cada $x\in X$, $\|P_nx-x\|\to 0$ cuando $n\to\infty$.
<!-- \end{itemize} -->


Además, dada una sucesión de operadores $(P_n)_n\subset\mathcal{B}(X)$ satisfaciendo $(a)$, $(b)$ y $(c)$, existe una base de Schauder de $X$ que tiene a $(P_n)_n$ como sucesión de proyecciones canónicas asociada.
:::

::: {.callout-note collapse="true" icon="false" class="proof-callout"}
## Demostración
<!-- ::: {.proof} -->
\hspace*{1mm}

::: {#cnj-1}
Antes de ver la demostración del Teorema @thm-proyecciones conviene recordar que se dice que un operador $P\in\mathcal{B}(X)$ es una *proyección* (lineal y continua) si $P^2\equiv PP=P$. En tal caso, $I-P$ también es una proyección. Además, $P(X)={\rm ker}\,(I-P)$, luego $P$ restringido a $P(X)$ es la identidad. Análogamente, ${\rm ker}\,P=(I-P)(X)$. Es evidente que si $P$ es una proyección no trivial ($P\neq 0$ y $P\neq I$), entonces $\|P\|\geq 1$ y $\|I-P\|\geq 1$.
:::

\noindent "$\Longrightarrow$"

(a) A la vista de (@eq-ProyCanon) es evidente que ${\rm dim}\,P_n(X)\leq n$. Además, $\{e_i\colon i\in\mathbb{N}\}$ es un conjunto linealmente independiente, pues si $\lambda_1e_1+\lambda_2 e_2+\cdots+\lambda_ne_n=0$, dado que 
$$
0=\sum_{i=1}^{\infty}0\,e_i=\sum_{i=1}^n{\lambda_ie_i} + \sum_{i=n+1}^{\infty}0\,e_i,
$$
la unicidad de los escalares que se exige en la definición de base de Schauder implica que $\lambda_i=0$ para todo $1\leq i\leq n$.  Por tanto, $\dim\,P_n(X)=n$.

(b) A la vista de (@eq-ProyCanon) es evidente que $P_nP_m=P_mP_n=P_{\min\{n,m\}}$.

(c) Dado que $(P_n(x))_n$ es la sucesión de sumas parciales de la serie (convergente) que coincide con $x$, por definición, $\|P_n(x)-x\|\to 0$ cuando $n\to\infty$.
\medskip

\noindent"$\Longleftarrow$"

Indicamos a continuación las ideas claves de la prueba. Se detallan todos los pasos de manera más pormenorizada al final de este epígrafe (en la página \pageref{D:proyecciones}).

Sea $P_0\equiv 0$ la aplicación nula y consideremos, para cada $i\in I$, un vector $e_i\in P_i(X)\cap 
{\rm ker}\,P_{i-1}$. En tal caso, para cada $x\in X$ se tiene que  
$$
x=\lim_{n\to\infty}{P_n(x)}=\lim_{n\to\infty}\sum_{i=1}^nP_i(x) - P_{i-1}(x)=  \sum_{i=1}^\infty a_ie_i,
$$  
ya que $\dim\,P_i(X)/P_{i-1}(X)=1$. La unicidad de la sucesión de escalares $(a_i)_i$ exigida en la definición de base de Schauder es consecuencia de que $a_ie_i=P_i(x)-P_{i-1}(x)$ para cada $i\in\mathbb{N}$.

<!-- ::: -->
:::

El lector podrá notar que la idea detrás de esta caracterización es muy interesante ---y bella---: para construir las bases del espacio total se parte de un espacio de dimensión finita y se va haciendo más grande hasta que, en una especie de convergencia espacial, se construye una sucesión de espacios que se aproxima cada vez más al espacio total. Nos gustaría incidir en esta idea porque guarda una estrecha relación con la filosofía del Análisis Matemático: estudiar aquello que no comprendemos fraccionándolo primero en aquello que sí conocemos y extrapolando luego mediante el uso de límites sus propiedades.

Además, remarca de nuevo la idea principal de este Trabajo Fin de Grado: las bases de Schauder pretenden ser bases de Hamel que admiten sumas infinitas, es decir, *límites* de bases de Hamel.

Veamos ahora un resultado que abre las puertas a lo que será nuestro ámbito de estudio: los espacios *completos*.


<!-- \begin{proposition}[Condición suficiente para ser base de Schauder de la compleción $\widehat{X}$ de $X$]\label{P:1.4}\hspace*{1mm}\\
Si
\begin{equation}\label{eq:acotacion}
    \sup_{n\in\mathbb{N}}\|P_n\|<\infty
\end{equation}
la sucesión $(e_i)_i$ también es una base de Schauder de la compleción $\widehat{X}$ de $X$. -->

::: {#prp-1.4} 

## Condición suficiente para ser base de Schauder de la compleción de $X$, $\ \widehat X$
\hspace*{1mm}

Si se verifica 
$$
\sup_{n\in\mathbb{N}}\|P_n\|<\infty
$$ {#eq-acotacion}
la sucesión $(e_i)_i$ también es una base de Schauder de la compleción $\widehat{X}$ de $X$.
:::


::: {.callout-note collapse="true" icon="false" class="proof-callout"}
## Demostración

\hspace*{1cm}

Consideremos, para cada $n\in\mathbb{N}$, la extensión continua de $P_n$ a $\widehat{X}$; es decir, para cada $\widehat{x}\in\widehat{X}$, definimos $\widehat{P}_n(\widehat{x})= \lim_{k\to\infty}P_n(x_k)$, siendo $(x_k)_k\subset X$ cualquier\footnote{Las proyecciones canónicas $P_n$ son continuas. Por tanto, si $(x_k)_k$ e $(y_k)_k$ son dos sucesiones convergentes a $\widehat{x}$, entonces $\widehat{P}_n(x_k-y_k)\to 0$ cuando $k\to\infty$ y equivalentemente $\lim_{k\to\infty}P_n(x_k)=\lim_{k\to\infty}P_n(y_k)$.} sucesión convergente a $\widehat{x}$.

Veamos que se cumplen las propiedades $(a)$, $(b)$ y $(c)$ del enunciado del Teorema @thm-proyecciones.


(a) Atendiendo a la definición de $\widehat{P}_n$, resulta evidente que 
$\widehat{P}_n(\widehat{X})\subset\overline{P_n(X)}$. Además, como ---por hipótesis--- $P_n(X)$ es un subespacio vectorial de dimensión finita, en particular es cerrado, luego $P_n(X)=\overline{P_n(X)}$. Por tanto $\widehat{P}_n(\widehat{X})\subset P_n(X)$.

    Por otra parte, dado que $P_n(X)=\widehat{P}_n(X)\subset\widehat{P}_n(\widehat{X})$, concluimos finalmente que $P_n(\widehat{X})$ es un espacio vectorial de dimensión $n$, ya que ---por hipótesis--- ${\rm dim}\,P_n(X)=n$. 
    
 (b) Dado $\widehat{x}\in \widehat{X}$ arbitrario pero fijado, existe $(x_k)_k\subset X$ tal que $x_k\to\widehat{x}$ cuando $k\to\infty$. Así pues, para $m$, $n\in\mathbb{N}$ cualesquiera,
$$
\begin{align*}
\widehat{P}_n\widehat{P}_mx & = \lim_{k \to\infty}{\widehat{P}_n\widehat{P}_mx_k} = \lim_{k \rightarrow\infty}{\widehat{P}_nP_mx_k} = \lim_{k \rightarrow\infty}{P_nP_mx_k}\\ & =  \lim_{k \rightarrow\infty}{P_mP_nx_k} = \lim_{k \rightarrow\infty}{\widehat{P}_m\widehat{P}_nx_k} = \widehat{P}_m\widehat{P}_nx,
\end{align*}
$$  
por lo que $\widehat{P}_n\widehat{P}_m=\widehat{P}_m\widehat{P}_n$. La igualdad $\widehat{P}_n\widehat{P}_m=\widehat{P}_{\min\{n,m\}}$ es consecuencia evidente de lo anterior y de la hipótesis $P_nP_m=P_{\min\{n,m\}}$.


(c) Conviene observar inicialmente que, para cada $n\in\mathbb{N}$, se tiene que $\|\widehat{P}_n\|\leq\|P_n\|$. En efecto, pues para cualquier $\widehat{x}\in\widehat{X}$ se tiene que
$$
\|\widehat{P}_n(\widehat{x})\| = \|\lim_{k \to \infty}P_n(x_k)\| = \lim_{k\to \infty}\|P_n(x_k)\| \leq \lim_{k \to \infty}\|P_n\|\|x_k\| = \|P_n\|\|\widehat{x}\|,
$$
siendo $(x_k)_k\subset X$ una sucesión tal que $x_k\to \widehat{x}$ cuando $k\to\infty$.

    Así pues, dado $\widehat{x}\in\widehat{X}$ arbitrario pero fijado, considerando $(x_k)_k\subset X$ tal que $x_k\to \widehat{x}$ cuando $k\to\infty$, tenemos que
    $$
    \begin{align*}   
        \|\widehat{x}-\widehat{P}_n\widehat{x}\|&=\|\widehat{x}-x_{k}+x_{k}-\widehat{P}_nx_{k}+\widehat{P}_nx_{k}-\widehat{P}_n\widehat{x}\|\\ 
        &\leq\|\widehat{x}-x_{k}\|+\|x_{k}-P_nx_{k}\|+\|\widehat{P}_nx_{k}-\widehat{P}_n\widehat{x}\|\\ 
        &\leq\|\widehat{x}-x_{k}\|+\|x_{k}-P_nx_{k}\|+\|\widehat{P}_n\|\,\|x_{k}-\widehat{x}\|\\
        &\leq\|\widehat{x}-x_{k}\|+\|x_{k}-P_nx_{k}\|+\sup_{n\in\mathbb{N}}\|\widehat{P}_n\|\,\|x_{k}-\widehat{x}\|\\
        &\leq \|\widehat{x}-x_{k}\|+\|x_{k}-P_nx_{k}\|+\sup_{n\in\mathbb{N}}\|P_n\|\,\|x_{k}-\widehat{x}\|.
    \end{align*}
    $$
    La condición $x_k\to \widehat{x}$ cuando $k\to\infty$ asegura la existencia de $k_\varepsilon\in\mathbb{N}$ de modo que si $k\geq k_\varepsilon$, entonces
    $$
    \|\widehat{x}-x_{k}\|<\dfrac{\varepsilon}{3}\quad\text{y}\quad \sup_{n\in\mathbb{N}}\|P_n\|\,\|x_{k}-\widehat{x}\|<\dfrac{\varepsilon}{3}.
    $$
    Por otra parte, dado que $(P_n)_n$ es una sucesión de proyecciones canónicas, las sucesión $(P_n)_n$ satisface la propiedad $(b)$ del enunciado del Teorema @thm-proyecciones, luego existe $N_{k_\varepsilon}\in\mathbb{N}$ de modo que si $n\geq N_{k_\varepsilon}$ entonces
    $$
    \|x_{k}-P_nx_{k}\|<\dfrac{\varepsilon}{3}.
    $$
    
    Por tanto, $\|\widehat{x}-\widehat{P}_n\widehat{x}\|<\varepsilon$ si $n\geq N_{k_\varepsilon}$; es decir, $\|\widehat{x}-\widehat{P}_n\widehat{x}\|\to 0$ cuando $n\to\infty$.\qedhere

:::



::: {#cnj-2}

\hspace*{1cm}

La condición (@eq-acotacion) sugiere definir
$$
\vertiii{x}=\sup_n\|P_nx\|\quad\text{para cada $x\in X$.}
$$
Comprobar que $\vertiii{\cdot}$ define una norma en $X$ es muy sencillo:

::: {.lista-n}
1. $\vertiii{x}\geq 0$ trivialmente y $0=\vertiii{x}=\sup_{n}{\|P_nx\|}$ implica que  $\|P_nx\|=0$ para todo $n\in\N$, pero como $\|\!\cdot\!\|$ es una norma, podemos deducir que $P_nx=0$ para todo $n$, de donde se sigue finalmente que $x=0$ por ser $(e_i)_i$ una base de Schauder.

2. $\vertiii{\lambda x}=\sup_n\|P_n(\lambda x)\|=\sup_n|\lambda|\,\|P_nx\|=|\lambda|\, \sup_n\|P_nx\|=\lambda\,\vertiii{x}$.

3. Dado que $\|P_nx+P_ny\|\leq \|P_n\|+\|P_ny\|$,
$$
\begin{align*}
    \vertiii{x+y}&=\sup_n\|P_n(x+y)\|=\sup_n\|P_nx + P_ny\|\leq\sup_n(\|P_nx\|+\|P_ny\|)\\ 
    &\leq\sup_n\|P_nx\|+\sup_n\|P_ny\|= \vertiii{x} + \vertiii{y}.
\end{align*}
$$
:::

:::

