project:
  type: book
  output-dir: docs

# filters: 
  # - first-line-indent

lang: es

book:
  title: "Bases de Schauder en espacios de Banach"
  author: "Iker Rodriguez Rodriguez"
  date: "Junio 2026"
  chapters:
    - index.qmd
    - resumen.qmd
    - introduccion.qmd
    - part: 01_Conceptos_intro.qmd
      chapters: 
        - 01_Conceptos-1.qmd
        - 01_Conceptos-2.qmd
    - part: 02_reflexivos_intro.qmd
      chapters: 
        - 02_reflexivos-1.qmd
        - 02_reflexivos-2.qmd 

    - part: 03_sucesiones_basicas_intro.qmd
      chapters:
        - 03_sucesiones_basicas-1.qmd
        - 03_sucesiones_basicas-2.qmd
        - 03_sucesiones_basicas-3.qmd
        - 03_sucesiones_basicas-4.qmd
    - Bibliografia.qmd

bibliography: referencias.bib
csl: ieee.csl


crossref:
  # custom:
  #   - key: obs
  #     kind: float
  #     reference-prefix: "Observación"
  #     caption-prefix: "Observación"
  #     latex-env: remark
  eq-prefix: ""

language: 
  crossref-prp-prefix: ""
  crossref-thm-prefix: ""
  crossref-def-prefix: ""
  crossref-cnj-title: "Observación"
  crossref-cnj-prefix: ""

# indent: false
# first-line-indent:
#   remove-after-class:
#     - proof     
#     - thm       
#     - obs       
#     - prp


format:
  html:
    theme:
      - cosmo
      - brand
    css: estilos.css
    include-in-header: macros-mathjax.html
  # pdf:
  #   documentclass: scrreprt
  #   include-in-header: 
  #     - 0_preambulo.tex
  #     - macros.tex
  #   latex_engine: xelatex



