project:
  type: book
  output-dir: docs

lang: es

book:
  title: "Bases de Schauder en espacios de Banach"
  author: "Iker Rodriguez Rodriguez"
  date: "Junio 2026"
  chapters:
    - index.qmd
    - resumen.qmd
    - introduccion.qmd
    - 01_Conceptos.qmd
    - Bibliografia.qmd

bibliography: referencias.bib
csl: ieee.csl


crossref:
  # custom:
  #   - key: obs
  #     kind: float
  #     reference-prefix: "Observación"
  #     caption-prefix: "Observación"
  #     latex-env: remark
  eq-prefix: ""

language: 
  crossref-prp-prefix: ""
  crossref-cnj-title: "Observación"
  crossref-cnj-prefix: ""

format:
  html:
    theme:
      - cosmo
      - brand
    css: estilos.css
    include-in-header: macros-mathjax.html
  pdf:
    documentclass: scrreprt
    include-in-header: 
      - 0_preambulo.tex
      - macros.tex
    latex_engine: xelatex



