# Introducción {.unnumbered}
\newline

Desde el inicio de la matemática moderna, con Descartes, hemos tenido el objetivo de asignar a los objetos de nuestro estudio una secuencia de cifras con las que poder simplificar dichos objetos y embeberlos en el mundo de los números, tratándolos así con todo el poder teórico de las matemáticas. Dio inicio esta tentativa con las primeras coordenadas *cartesianas* ---así designadas en honor a su promotor--- que movilizaron el motor de la producción matemática haciéndolo más fructífero en los últimos $500$ años que en los previos $3\,300$ que hay desde las primeras ternas pitagóricas mesopotámicas conocidas.

Es con esa filosofía en mente que surge la idea de realizar tal tentativa no ya con objetos físicos o con coordenadas finitas, sino con el poder del infinito. El objetivo es ahora el estudio de objetos mucho más abstractos: las funciones ---lo cual trajo consigo el problema de las inifitas dimensiones---.

Al principio, el estudio se reducía a las funciones de $\mathcal{C}^\infty$ o infinitamente diferenciables ---las conocidas como series de Taylor, 1715, que fallaron en generar todo el espacio y se reducían a las funciones analíticas---. Con el tiempo, la idea fue madurando y se quiso ampliar el domino de validez a todas las funciones continuas, aún cuando no se tenía muy claro qué era una función continua todavía ---de aquí surgieron las series de Fourier, conocidas ya a principios del siglo XIX y que resultarían en una base no para las funciones continuas con la norma de la convergencia uniforme, sino para el espacio $L^2$ con la norma *euclidiana* $\|\!\cdot\!\|_2$---.

Con el final del siglo XIX y la llegada del XX comenzaron a darse los mayores avances en este campo. Hilbert, Schmidt y Riesz---entre muchos otros--- comenzaron el estudio del espacio de las funciones de cuadrado integrable y consiguieron extraer ciertas nociones geométricas muy similares a las de los espacios euclidianos de dimensión finita, como por ejemplo la ortogonalidad. El concepto creció y se estableció la abstracción de los espacios de Hilbert ---término acuñado por von Neumann---, cuyo principal cometido y éxito es generalizar los espacios euclidianos a dimensión infinita respetando la existencia de sistemas ortonormales que generan la totalidad del espacio. Surgió así el estudio sistemático de la noción de base en dimensión infinita. 

De forma paralela, Haar construyó un sistema ---el conocido como sistema de Haar--- de funciones que sirven de base no sólo para el espacio $L^2$, que ya tenía una base dada por las series de Fourier que además funcionaba por ser este un espacio de Hilbert, sino de todos los espacios $L^p$, con $1\leq p<\infty$ que  no son Hilbertianos. Poco después, Georg Faber demostró la existencia de una base para el espacio de las funciones continuas con la norma uniforme. 

Todo este impulso histórico se cristalizó en la tesis de $1923$ de un joven matemático polaco, Juliusz Schauder. Él dio rigor y formalismo a la idea de una generalización de todo lo anterior introduciendo el concepto hoy en día conocido, en su honor, como *bases de Schauder*: un avance más en el entendimiento de la estructura de los espacios de funciones inspirado en el objetivo de Descartes de simplificar el estudio de cualquier ente a un sistema de coordenadas coherente del que se puedan extraer conclusiones.

Es por querer dar valor a esta idea tan matemática que en el presente Trabajo Fin de Grado queremos dar un repaso a algunos de los resultados que las bases de Schauder han ayudado a probar y comprender.

En el Capítulo [1](01_Conceptos_intro.html#cap-1) nos centraremos en la definición de lo que es una base de Schauder y caracterizaremos su existencia; también incluiremos algunos comentarios sobre el problema de la existencia de base para un espacio de Banach.

En el Capítulo [2](02_reflexivos_intro.html#cap-2) estudiaremos la relación entre las bases de Schauder y el espacio dual, demostrando el primer gran resultado del trabajo: la caracterización de aquellos espacios de Banach que son reflexivos y admiten base de Schauder.

En el Capítulo [3](03_sucesiones_basicas_intro.html#sec-SucesionesBasicas) estudiaremos las conocidas como sucesiones básicas, que no son más que bases de Schauder del espacio ---quizás menor que el total--- que generan. También hablaremos sobre la noción equivalencia para bases de Schauder.

En el Capítulo [4](04_bases_incondicionales_intro.html#cap-4) estudiaremos aquellas bases de Schauder que son incondicionales; es decir, es indiferente el orden que consideremos a la hora de estudiar la convergencia de la serie que define a cada vector del espacio. Caracterizaremos los espacios de Banach reflexivos con base incondicional.

En el Capítulo [5](05_incomparabilidad_intro.html#cap-5) daremos por finalizada nuestra tentativa empleando la teoría de las bases de Schauder desarrollada a lo largo del trabajo para estudiar la estructura interna de los espacios de sucesiones $\ell_p$ con $1\leq p<\infty$, con el objetivo de dar a entender como de distintos son entre sí. 

A mayores, queremos dejar patente que las bases de Schauder no son en absoluto una construcción artificiosa, sino que generalizan muy naturalmente a las bases de Hamel de los espacios de dimensión finita. Es por ello que iremos comparando sus propiedades en algunos capítulos para dejar claro el origen algebraico que tiene detrás esta idea y que tan bien resume la filosofía del Análisis Funcional de fusionar conceptos algebraicos con nociones topológicas para el estudio de las funciones.

::: {style = "text-align: right"}
Santiago de Compostela, julio de 2025.
:::
